### ISSUE TITLE
Figure out specifics of what we want to analyse

### ISSUE THREAD

**Issue by 2rius** [2rius/safer-driving#9]
* all 3 members assigned ( @ChrBank @2rius @Mads0709 )

- [ ] Corelation or 'Cause and Effect'?
- [ ] Develop dataset of what we CAN analyse (from OBD, Maps API, etc) and what we SHOULD analyse (relevance from interviews?)
- [ ] (Optional) Set up mock data for a test analysis

**Comment by 2rius** [comment]
Sheet of dataset: https://docs.google.com/spreadsheets/d/1uPMxucEfqxZuSgqFm27wjJqTILTjEt8ZDQvI55P33q4/edit#gid=0

**Comment by ChrBank** [comment]
Analyze the cause and effect with sounds to alert drivers, and see the causes of their effects for safer driving.
